import { describe, expect, it } from "vitest";
import fixture from "./__fixtures__/tab.fixture.json";
import { STAGES, STAGE_LABELS, type TabJson } from "./types";

/**
 * The fixture is generated by the real worker emitter and diffed against it
 * in worker/tests/test_contract.py; tsc checks it against TabJson below, and
 * pytest checks TabJson against the emitter's actual keys. Any drift in the
 * tab.json contract fails on one side or the other.
 */
describe("worker/web contract", () => {
  it("the committed fixture satisfies TabJson", () => {
    const tab: TabJson = fixture;
    expect(tab.bpm).toBe(120);
    expect(tab.notes.length).toBeGreaterThan(0);
    expect(tab.chords.length).toBeGreaterThan(0);
    expect(Object.keys(tab.notes[0]).sort()).toEqual([
      "amplitude",
      "duration",
      "fret",
      "pitch",
      "start",
      "string",
    ]);
    expect(Object.keys(tab.chords[0]).sort()).toEqual(["end", "name", "start"]);
  });

  it("every pipeline stage has a UI label", () => {
    for (const stage of STAGES) {
      expect(STAGE_LABELS[stage]).toBeTruthy();
    }
  });
});
