import type { Metadata } from "next";
import Link from "next/link";
import { zenKaku } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "TabForge — YouTube to Guitar Tab",    description:
      "Paste a YouTube link and download a Guitar Pro (.gp) tab generated by an audio transcription pipeline.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={zenKaku.variable}>
      <body>
        <div className="shell">
          <nav className="top">
            <Link href="/" className="brand">
              Tab<span>Forge</span>
            </Link>
            <Link href="/" className="link">
              New tab
            </Link>
            <Link href="/library" className="link">
              Library
            </Link>
          </nav>
          {children}
          <footer className="note">
            Tabs are machine-generated from audio and will contain mistakes — they are
            meant as a starting point; open the .gp file in Guitar Pro to edit them. Audio
            is processed locally for personal use; respect the rights of the artists.
          </footer>
        </div>
      </body>
    </html>
  );
}
